# Generated by Django 6.0.6 on 2026-06-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
