# Generated by Django 6.0.6 on 2026-06-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_datetime_transaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='subCategory',
            new_name='subcategory',
        ),
    ]
