# Generated by Django 6.0.6 on 2026-07-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_subcategory_transaction_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayletTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='paylet_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
