# Generated by Django 6.0.6 on 2026-07-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paylettemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylet',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylets', to='finance.transaction'),
        ),
    ]
